// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ymfejiadehbsezxmgtuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltZmVqaWFkZWhic2V6eG1ndHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTMyMzgsImV4cCI6MjA2ODY4OTIzOH0.dOyY92Jzgy1_AG4O1klOcFQ5YcwuAFjHbbzwEUDcLzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Phase 3: Safe localStorage wrapper for iOS
const safeLocalStorage = (() => {
  try {
    if (typeof window !== 'undefined' && window.localStorage) {
      // Test if we can actually use it
      window.localStorage.setItem('__test__', '1');
      window.localStorage.removeItem('__test__');
      return window.localStorage;
    }
  } catch (e) {
    console.warn('localStorage unavailable, using memory storage');
  }
  
  // Fallback in-memory storage
  const memoryStorage = {
    data: {} as Record<string, string>,
    getItem(key: string) { return this.data[key] || null; },
    setItem(key: string, value: string) { this.data[key] = value; },
    removeItem(key: string) { delete this.data[key]; },
  };
  return memoryStorage;
})();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeLocalStorage as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});